---
- name: Install authbind
  apt:
    name: authbind

# https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443#892391
- name: Allow non-root process to bind to web ports
  file:
    path: '{{item}}'
    state: touch
    mode: '0777'
  with_items:
    - /etc/authbind/byport/80
    - /etc/authbind/byport/443

- name: Create a Buildbot master
  command: |
    sudo --user {{application_user}} \
        buildbot create-master {{home_dir}}/master
  args:
    chdir: '{{home_dir}}'
    creates: '{{home_dir}}/master'

- name: Insert Buildbot worker definition file
  template:
    src: workers.json.j2
    owner: '{{application_user}}'
    group: '{{application_group}}'
    dest: '{{home_dir}}/master/workers.json'
  notify:
    - Restart "build master" service

- name: Create directory to store secrets
  file:
    path: '{{home_dir}}/master/secrets'
    state: directory
    owner: '{{application_user}}'
    group: '{{application_group}}'
    mode: 0700

- name: Insert secrets
  copy:
    content: '{{item.value}}'
    dest: '{{home_dir}}/master/secrets/{{item.name}}'
    owner: '{{application_user}}'
    group: '{{application_group}}'
    mode: 0700
  with_items:
    - name: sauce_labs_user
      value: '{{sauce_labs_user}}'
    - name: sauce_labs_key
      value: '{{sauce_labs_key}}'
    - name: oauth_github_client_id
      value: '{{oauth_github_client_id}}'
    - name: oauth_github_client_secret
      value: '{{oauth_github_client_secret}}'
    # The following value isn't sensitive in nature, but it is deployed to the
    # build master as a "secret" in order to normalize handling of
    # configuration data.
    - name: oauth_github_org_pattern
      value: '{{oauth_github_org_pattern}}'

# The "requests" module is a soft requirement of Buildbot, necessary only when
# using the OAUth functionality.
- name: Install "requests" Python package
  pip:
    name: requests

- name: Copy Buildbot configuration files into place
  copy:
    src: ../src/master/
    dest: '{{home_dir}}/master'
  notify:
    - Restart "build master" service

- name: Define a system service
  template:
    src: buildbot-master.service.j2
    dest: /etc/systemd/system/buildbot-master.service
  notify:
    - Restart "build master" service

- name: Enable system service
  systemd:
    name: buildbot-master
    enabled: true

- name: Install script for uploading results
  copy:
    src: ../../../src/scripts/upload-wpt-results.py
    dest: /usr/local/bin/upload-wpt-results.py
    mode: 0755
