---
- hosts: all
  gather_facts: False
  become: True
  pre_tasks:
    - name: Install Python for Ansible
      run_once: is_development
      raw: |-
        test -e /usr/bin/python || \
          (apt -y update && sudo apt install -y python-minimal)
      changed_when: False
    - name: Install pip
      run_once: is_development
      apt:
        name: python-pip
  vars_files:
    - vars/main.yml
- hosts: buildbot-master
  become: true
  roles:
    - user-accounts
    - buildbot-master
    - google-cloud-platform
  vars_files:
    - vars/main.yml
    - vars/master.yml
    - vars/vault
- hosts: buildbot-workers
  become: true
  roles:
    - user-accounts
    - buildbot-worker
    - web-browsers
    - sauce-labs
    - wpt-cli
  vars_files:
    - vars/main.yml
