---
# In Ubuntu 16.04, open file limits are set via two independent configuration
# files.
#
# https://ro-che.info/articles/2017-03-26-increase-open-files-limit
- name: Raise limit on number of open files (systemd settings)
  lineinfile: dest=/etc/systemd/system.conf
    regexp="DefaultLimitNOFILE"
    line="DefaultLimitNOFILE=65536"
    state=present

- name: Raise limits on number of open files (PAM settings)
  lineinfile:
    dest: /etc/security/limits.conf
    line: '{{item}}'
  with_items:
    - '* soft nofile 65536'
    - '* hard nofile 65536'

- name: Create directory to store downloaded files
  file:
    name: ~/downloads
    state: directory

- name: Download Sauce Connect
  get_url:
    url: https://saucelabs.com/downloads/sc-4.5.0-linux.tar.gz
    dest: ~/downloads
    checksum: sha1:d257113657d9ba48029037c5c9a50d81d9e730ff

- name: Unpack Sauce Connect
  unarchive:
    src: ~/downloads/sc-4.5.0-linux.tar.gz
    dest: ~/downloads
    creates: ~/downloads/sc-4.5.0-linux/bin/sc
    remote_src: true

- name: Install Sauce Connect
  copy:
    src: ~/downloads/sc-4.5.0-linux/bin/sc
    dest: /usr/local/bin
    mode: 0755
    remote_src: true

- name: Install wrapper for Sauce Connect
  copy:
    src: files/sc-no-ssl-bump-domains
    dest: /usr/local/bin
    mode: 0755

  # This configuration is a short-term workaround recommended by Sauce Labs. It
  # shold be removed once the underlying issue has been resolved b that
  # service.
  #
  # https://github.com/web-platform-tests/results-collection/issues/557
- name: Extend hosts file with short-term workaround
  lineinfile:
    dest: /etc/hosts
    line: 162.222.75.227 saucelabs.com
