---
- hosts: all
  #remote_user: username specified in /etc/ansible/hosts
  become: yes
  become_user: root
  vars_files:
    - vars/main.yml
    - vars/vault
  tasks:
  - name: Set authorized key, removing all the authorized key already set
    authorized_key:
     user: root
     key: '{{ item }}'
     state: present
     exclusive: True
    with_file:
     - public_keys/web-platform

  - name: Create directory to store keys
    file:
      name: /root/keys
      state: directory

  - name: Download keys for external package repositories
    get_url:
      url: '{{item.key_url}}'
      dest: /root/keys/{{item.name}}
    with_items: '{{external_packages}}'

  - name: Install keys for external package repositories
    command: apt-key add /root/keys/{{item.name}}
    with_items: '{{external_packages}}'

  - name: Add apt sources
    lineinfile:
      dest: '/etc/apt/sources.list.d/{{item.name}}.list'
      line: '{{item.repository}}'
      create: true
    with_items: '{{external_packages}}'

  - name: update package repository
    command: apt-get update

  - name: Infer current kernel Linux version
    command: uname -r
    register: kernel_version

  - name: Install kernel Linux headers
    apt:
      name: linux-headers-{{kernel_version.stdout}}
      state: present
    notify: Restart system

  - name: install the various packages we need
    apt:
      name: '{{ item }}'
      state: present
    with_items:
      - curl
      - dtrx
      - emacs-nox
      - firefox
      - git
      - google-chrome-stable
      - google-cloud-sdk
      - htop
      - libnss3-tools
      - nvidia-367
      - nvidia-375
      - nvidia-384
      - python-pip
      - python2.7
      - rsync
      - screen
      - unattended-upgrades
      - virtualenv
      - xauth
      - xvfb

  - name: Create directory to store downloaded files
    file:
      name: ~/downloads
      state: directory

  - name: Download Mozilla Geckodriver
    get_url:
      url: https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
      dest: ~/downloads/

  - name: Install Mozilla Geckodriver
    unarchive:
      src: ~/downloads/geckodriver-v0.19.1-linux64.tar.gz
      dest: /usr/local/bin
      remote_src: true

  - name: Download Google Chromedriver
    get_url:
      url: https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
      dest: ~/downloads/

  - name: Install Google Chromedriver
    unarchive:
      src: ~/downloads/chromedriver_linux64.zip
      dest: /usr/local/bin
      remote_src: true

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: Restart ssh

  - name: checkout the wptdashboard project
    git:
      repo: 'https://github.com/w3c/wptdashboard.git'
      dest: ~/wptdashboard
      force: yes

  - name: checkout the web-platform-tests
    git:
      repo: 'https://github.com/w3c/web-platform-tests.git'
      dest: ~/web-platform-tests
      force: yes

  - name: install python requirements
    pip:
      requirements: ~/wptdashboard/requirements.txt

  - name: make python virtualenv
    pip:
      name: virtualenv
      virtualenv: ~/web-platform-tests/_venv

  - name: make sure we can open enough files
    lineinfile: dest=/etc/systemd/system.conf
      regexp="DefaultLimitNOFILE"
      line="DefaultLimitNOFILE=65536"
      state=present

  - name: copy various files in /files/root/ to /root/
    copy:
      src: files/root/browser-runner.sh
      dest: /root/browser-runner.sh
      owner: root
      group: root
      mode: 0755

  - name: set up browser-runner to run tests for a browser
    lineinfile: dest=/root/browser-runner.sh
      regexp="export BROWSER"
      line="export BROWSER={{ browser }}"
      state=present

  - name: ensure we have the latest google-sdk
    command: pip install --upgrade google-cloud
    async: 0
    poll: 0
    ignore_errors: true

  - name: make a cronjob to run browser-runner.sh
    cron:
      name: "run browsers"
      minute: "*/1"
      job: "/root/browser-runner.sh > /root/browser-runner.log 2>&1"

  - name: make a cronjob to remove browser-running.txt at boot
    cron:
      name: "a job for reboot"
      special_time: reboot
      job: "rm /root/browser-running.txt"

  - name: put the running.ini file in place
    template:
      src: files/root/running.ini.j2
      dest: /root/wptdashboard/run/running.ini
      owner: root
      group: root
      mode: 0755

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
    - name: Restart system
      command: /sbin/shutdown -r +1
