---
- name: Copy Python requirements file into place
  copy:
    src: requirements.txt
    dest: '{{home_dir}}'

- name: Install Python dependencies
  pip:
    requirements: '{{home_dir}}/requirements.txt'

- name: Create a Buildbot worker
  command: |
    sudo --user {{application_user}}
        buildbot-worker create-worker
          --allow-shutdown file
          {{home_dir}}/worker {{master_hostname}} {{application_user}} {{buildbot_worker_password}}
  args:
    chdir: '{{home_dir}}'
    creates: '{{home_dir}}/worker'

- include_tasks: unattended_upgrades.yml

- name: Insert description of worker system
  template:
    src: host.j2
    owner: '{{application_user}}'
    group: '{{application_group}}'
    dest: '{{home_dir}}/worker/info/host'
  notify:
    - Restart "build worker" service

- name: Define a system service
  template:
    src: buildbot-worker.service.j2
    dest: /etc/systemd/system/buildbot-worker.service
  notify:
    - Reload SystemD daemon

- name: Install script for clearing ports
  copy:
    src: ../../src/scripts/kill-by-port.sh
    dest: /usr/local/bin/kill-by-port.sh
    mode: 0755

- name: Install script for running WPT
  copy:
    src: ../../src/scripts/run-and-verify.py
    dest: /usr/local/bin/run-and-verify.py
    mode: 0755

- name: Enable and start system service
  systemd:
    name: buildbot-worker
    enabled: true
    state: started
