---
- name: Restart "build worker" service
  shell: |
    #!/bin/bash
    set -e
    uname=$(uname)

    if [ $uname = "Linux" ]; then
      systemctl restart buildbot-worker
    elif [ $uname = "Darwin" ]; then
      launchctl unload -w /Library/LaunchDaemons/start.buildbot.worker.plist || true
      launchctl load -w /Library/LaunchDaemons/start.buildbot.worker.plist
    else
      echo Unrecognized system: $uname >&2
      exit 1
    fi
